### ISSUE TITLE
Prepare installer for deployment

### ISSUE THREAD

**Issue by Elvin-Arrow** [Elvin-Arrow/Project-Lighthouse#8]
Ideally have a release candidate on GitHub repo itself

**Comment by Elvin-Arrow** [comment]
What we need is a package installer that houses not on the IDE but also the dependencies as stated by the home readme section.

**Comment by theQureshi** [comment]
Yes, got it. I was looking into how to build Windows installers. I’ll look more into it.

**Comment by Elvin-Arrow** [comment]
You can look into how Microsoft or Atom makes installers for `electron.js` based applications.
